export const SHIPPING_ADDRESS_FAIL = "SHIPPING_ADDRESS_FAIL";
export const SHIPPING_ADDRESS_SUCCESS = "SHIPPING_ADDRESS_SUCCESS";
export const SHIPPING_ADDRESS_REQUEST = "SHIPPING_ADDRESS_REQUEST";

export const SHIPPING_ADDRESS_POST_SUCCESS = "SHIPPING_ADDRESS_POST_SUCCESS";
export const SHIPPING_ADDRESS_POST_FAIL = "SHIPPING_ADDRESS_POST_FAIL";
export const SHIPPING_ADDRESS_POST_REQUEST = "SHIPPING_ADDRESS_POST_REQUEST";



